# Welcome to Numpy tutorial

****This file gonna use by Raj soon***

In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,37,7]], np.int64)

In [4]:
myarr[0,1]

np.int64(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

**Array creation methods in numpy**

*5 methods for creating arrays:*
1. Conversion from other python structures(ex- lists, tuples)
2. Intrinsic numpy array creation objects(ex- arange, ones, zeroes, etc.)
3. Reading arrays from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions(ex- random)

**Method 1** : Conversion from other python structures

In [7]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [8]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [9]:
listarray.dtype

dtype('int64')

In [10]:
listarray.shape

(3, 3)

In [11]:
np.array({34, 23, 23})

array({34, 23}, dtype=object)

In [13]:
 zeros = np.zeros((2, 5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1, 5, 12) 

*linear space de deta hai array mein*

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
emp = np.empty((4, 6))

In [23]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.86919378e-306,
        1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.37962320e-306, 1.29060871e-306,
        2.22518251e-306, 1.33511969e-306, 1.78022342e-306],
       [1.05700345e-307, 3.11525958e-307, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.02361614e-306, 1.78020848e-306, 1.78021527e-306,
        1.69119330e-306, 9.79101082e-307, 1.78020576e-306]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(3, 33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr = arr.ravel()

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.shape

(99,)

# Numpy Axis

1. In 1D, there is only 1 Axis -> Axis 0
2. In 2D, there are only 2 Axis -> Axis 0, Axis 1

In [39]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [40]:
ar = np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis = 0)

array([12,  8,  9])

In [43]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.flat

In [46]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [47]:
ar.ndim

2

ndim = no. of dimensions

In [48]:
ar.size

9

In [49]:
 ar.nbytes

72

In [50]:
one = np.array([1, 3, 4, 634, 2])

In [51]:
one.argmax()

np.int64(3)

In [52]:
one.argmin()

np.int64(0)

In [53]:
one.argsort()

array([0, 4, 1, 2, 3])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [56]:
ar.argmin()

np.int64(8)

In [57]:
ar.argmax()

np.int64(6)

In [58]:
ar.argmax(axis = 0)

array([2, 1, 1])

In [59]:
ar.argmax(axis = 1)

array([2, 2, 0])

In [60]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [61]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
ar2 = np.array([[1, 2, 1], [4, 0, 6], [8, 1, 0]])

In [66]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

*Numpy provide you the matrix operations*

In [67]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [69]:
ar.sum()

np.int64(29)

In [70]:
ar.max()

np.int64(7)

In [72]:
ar.min()

np.int64(0)

In [73]:
np.where(ar > 5)

(array([1, 2]), array([2, 0]))

In [74]:
type(np.where(ar > 5))

tuple

In [75]:
np.count_nonzero(ar)

8

In [76]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [77]:
import sys


In [78]:
py_ar = [0, 4, 55, 2]

In [79]:
np_ar = np.array(py_ar)

In [80]:
sys.getsizeof(1) * len(py_ar)

112

In [81]:
np_ar.itemsize * np_ar.size

32

Numpy attributes and methods link:- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

# Numpy basics finished